# Generated by Django 4.2.14 on 2024-07-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Открыта', 'Открыта'), ('Выполнена', 'Выполнена'), ('Просрочена', 'Просрочена')], default='Открыта', max_length=30),
        ),
        migrations.AddField(
            model_name='tasks',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='time_to_task',
            field=models.DateTimeField(null=True),
        ),
    ]
