# Generated by Django 4.2.14 on 2024-07-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_bureaus_list_alter_workers_bureau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='time_to_task',
        ),
        migrations.AlterField(
            model_name='workers',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tasks.bureaus_list'),
        ),
    ]
